apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "RAPP_NAME.name" . }}
  labels:
    {{- include "RAPP_NAME.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations:
    {{- include "RAPP_NAME.product-info" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "RAPP_NAME.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if and (eq .Values.updateStrategy.type "RollingUpdate") .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
{{- if .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
{{- end }}
{{- if .Values.updateStrategy.rollingUpdate.maxSurge }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
{{- end }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "RAPP_NAME.name" . }}
        app.kubernetes.io/name: {{ include "RAPP_NAME.name" . }}
        app.kubernetes.io/version: {{ include "RAPP_NAME.version" . }}
        helm.sh/chart: {{ template "RAPP_NAME.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service.cleartext/scraping: "true"
      annotations:
        {{- if not (semverCompare ">=1.30.0" .Capabilities.KubeVersion.GitVersion) }}
        container.apparmor.security.beta.kubernetes.io/RAPP_NAME: {{ include "RAPP_NAME.appArmorProfileAnnotation" . | default "runtime/default" }}
        {{- end }}
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
        prometheus.io/path: "{{ .Values.prometheus.path }}"
{{- include "RAPP_NAME.product-info" . | indent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if (index .Values "podPriority" "RAPP_NAME" "priorityClassName") }}
      priorityClassName: {{ (index .Values "podPriority" "RAPP_NAME" "priorityClassName") }}
      {{- end }}
      volumes:
        - name: platform-cacerts
          secret:
            secretName: {{ index .Values "platformCaCertSecretName" | quote }}
            defaultMode: 420
        - name: app-certs
          secret:
            secretName: {{ index .Values "appSecretName" | quote }}
            defaultMode: 420
        - name: kafka-cacerts
          secret:
            secretName: {{ index .Values "kafkaCaCertSecretName" | quote }}
            defaultMode: 420
      securityContext:
        fsGroup: {{include "RAPP_NAME.fsGroup" .}}
      hostPID: false
      hostIPC: false
      hostNetwork: false
      containers:
        - name: RAPP_NAME
          image: {{ template "RAPP_NAME.imagePath" (dict "imageId" "RAPP_NAME" "values" .Values "files" .Files) }}
          imagePullPolicy: {{ include "RAPP_NAME.registryImagePullPolicy" . | quote }}
          securityContext:
            {{- if semverCompare ">=1.30.0" .Capabilities.KubeVersion.GitVersion }}
            appArmorProfile:
              type: {{ include "RAPP_NAME.appArmorProfile.type" . | default "RuntimeDefault" }}
            {{- end }}
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
              - all
            {{- include "RAPP_NAME.seccomp-profile" . | indent 12 }}
            procMount: Default
          volumeMounts:
            - name: platform-cacerts
              mountPath: {{ index .Values "platformCaCertMountPath" | default .Values.instantiationDefaults.platformCaCertMountPath | quote }}
              readOnly: true
            - name: app-certs
              mountPath: {{ index .Values "appCertMountPath" | default .Values.instantiationDefaults.appCertMountPath | quote }}
              readOnly: true
            - name: kafka-cacerts
              mountPath: {{ index .Values "kafkaCaCertMountPath" | default .Values.instantiationDefaults.kafkaCaCertMountPath | quote }}
              readOnly: true
          env:
            - name: IAM_CLIENT_ID
              value: {{ index .Values "clientId" | quote }}
            - name: IAM_CLIENT_SECRET
              value: {{ index .Values "clientSecret" | quote }}
            - name: IAM_BASE_URL
              value: {{ index .Values "iamBaseUrl" | quote }}
            - name: LOG_ENDPOINT
              value: {{ index .Values "logEndpoint" | quote }}
            - name: CA_CERT_FILE_PATH
              value: {{ index .Values "platformCaCertMountPath" | default .Values.instantiationDefaults.platformCaCertMountPath | quote }}
            - name: CA_CERT_FILE_NAME
              value:  {{ index .Values "platformCaCertFileName" | quote }}
            - name: APP_KEY
              value: {{ index .Values "appKeyFileName" | quote }}
            - name: APP_CERT
              value: {{ index .Values "appCertFileName" | quote }}
            - name: APP_CERT_FILE_PATH
              value: {{ index .Values "appCertMountPath" | default .Values.instantiationDefaults.appCertMountPath | quote }}
            - name: KAFKA_CERT_MOUNT_PATH
              value: {{ index .Values "kafkaCaCertMountPath" | default .Values.instantiationDefaults.kafkaCaCertMountPath | quote }}
            - name: KAFKA_CERT_FILE_NAME
              value: {{ index .Values "kafkaCaCertFileName" | default .Values.instantiationDefaults.kafkaCaCertFileName | quote }}
            - name: CONSUMER_MESSAGE_BATCH_SIZE
              value: {{ index .Values "consumerMessageBatchSize" | default .Values.instantiationDefaults.consumerMessageBatchSize | quote }}
            - name: CONSUMER_TIMEOUT
              value: {{ index .Values "consumerTimeout" | default .Values.instantiationDefaults.consumerTimeout | quote }}
            - name: SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: CONTAINER_NAME
              value: {{ .Chart.Name }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TZ
              value: {{ template "RAPP_NAME.timezone" . }}
            - name: LOG_CTRL_FILE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "RAPP_NAME.name" . }}
                  key: logcontrol.json
            {{- include "RAPP_NAME.jaegerEnv" . | indent 12 }}
          ports:
            - name: http-metrics
              containerPort: 8050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /network-data-template-app/health/liveness
              port: 8050
          {{- if (index .Values "probes" "RAPP_NAME" "livenessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "RAPP_NAME" "livenessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "RAPP_NAME" "livenessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "RAPP_NAME" "livenessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "RAPP_NAME" "livenessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "RAPP_NAME" "livenessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "RAPP_NAME" "livenessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "RAPP_NAME" "livenessProbe" "timeoutSeconds") }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /network-data-template-app/health/readiness
              port: 8050
          {{- if (index .Values "probes" "RAPP_NAME" "readinessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "RAPP_NAME" "readinessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "RAPP_NAME" "readinessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "RAPP_NAME" "readinessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "RAPP_NAME" "readinessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "RAPP_NAME" "readinessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "RAPP_NAME" "readinessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "RAPP_NAME" "readinessProbe" "timeoutSeconds") }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.networkDataTemplateApp | nindent 12 }}
      {{- if include "RAPP_NAME.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "RAPP_NAME.pullSecrets" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ include "RAPP_NAME.terminationGracePeriodSeconds" . }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- include "RAPP_NAME.tolerations" . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | indent 8 }}
      {{- end }}
      nodeSelector: {{ include "RAPP_NAME.nodeSelector" . | nindent 6 -}}
