# 
# COPYRIGHT Ericsson 2025
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
openapi: 3.0.3
info:
  x-api-id: 6377a9c2-3a01-497a-b5d9-23dbbc65f7be
  x-audience: external-public
  title: Bulk Data Repository Discovery API
  description: This API allows to discover the Bulk data repository details with the endpoint containing optional QueryParams.
  version: 1.0.0
servers:
  - url: https://<eic-host>/dmm-data-catalog
tags:
  - name: Bulk Data Repository
    description: Bulk data repository host details
paths:
  /catalog/v1/bulk-data-repository/:
    get:
      tags:
        - Bulk Data Repository
      summary: Discover the Bulk data repository details
      description: This method is used to discover the Bulk data repository details with optional parameters
      operationId: queryAllBDR
      parameters:
        - name: name
          in: query
          description: name (Optional) value of the Bulk data repository
          schema:
            type: string
        - name: namespace
          in: query
          description: namespace (Optional) value of the Bulk data repository
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BulkDataRepositoryDTO'
              example:
                - accessEndpoints:
                    - "http://bdrhost.cluster.example.com"
                  clusterName: "clusterName"
                  fileFormatIds:
                    - 1
                  id: 1
                  name: "eric-data-object-storage-mn"
                  nameSpace: "namespace"
                  fileRepoType: "S3"
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CatalogResponse'
              example:
                message: "error message"
                timeStamp: "1970-01-01T00:00:00.000Z"
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CatalogResponse'
              example:
                message: "error message"
                timeStamp: "1970-01-01T00:00:00.000Z"
components:
  schemas:
    BulkDataRepositoryDTO:
      type: object
      properties:
        accessEndpoints:
          type: array
          items:
            type: string
        clusterName:
          type: string
        fileFormatIds:
          type: array
          items:
            type: integer
            format: int32
        id:
          type: integer
          format: int32
        name:
          type: string
        nameSpace:
          type: string
        fileRepoType:
          type: string
          enum: [S3, SFTP]
    CatalogResponse:
      type: object
      properties:
        message:
          type: string
        timeStamp:
          type: string
          format: date-time